"""initial models

Revision ID: 0230ec4103ea
Revises: 
Create Date: 2025-11-21 16:27:48.685984

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0230ec4103ea'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mechanics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('service_tickets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('issue_description', sa.String(length=255), nullable=False),
    sa.Column('amount_quoted', sa.Integer(), nullable=True),
    sa.Column('amount_charged', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ticket_mechanic',
    sa.Column('ticket_id', sa.Integer(), nullable=True),
    sa.Column('mechanic_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['mechanic_id'], ['mechanics.id'], ),
    sa.ForeignKeyConstraint(['ticket_id'], ['service_tickets.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ticket_mechanic')
    op.drop_table('service_tickets')
    op.drop_table('mechanics')
    # ### end Alembic commands ###
