"""Added inventory models

Revision ID: 64d702b9b961
Revises: 0230ec4103ea
Create Date: 2025-12-03 21:38:23.459910

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '64d702b9b961'
down_revision = '0230ec4103ea'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('inventory',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('price', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ticket_parts',
    sa.Column('ticket_id', sa.Integer(), nullable=True),
    sa.Column('part_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['part_id'], ['inventory.id'], ),
    sa.ForeignKeyConstraint(['ticket_id'], ['service_tickets.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ticket_parts')
    op.drop_table('inventory')
    # ### end Alembic commands ###
